### ISSUE TITLE
Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:native (default-cli) on project hello-javafx-maven-example: An error occurred while generating native deployment bundles: Not found MSVC dlls

### ISSUE THREAD

**Issue by MrTob** [javafx-maven-plugin/javafx-maven-plugin#395] opened 2022-02-20 21:50 UTC
Hey,
i wanted to create a native bundle with the `jfx:native` comand but i got this error
Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:native (default-cli) on project hello-javafx-maven-example: An error occurred while generating native deployment bundles: Not found MSVC dlls

I have installed: WiX Tootlset and Inno Setup compiler.
What is wrong?

**Comment by FibreFoX** [comment] 2022-02-20 23:15
Which JDK are you using? What shows `mvn -v`

**Comment by MrTob** [comment] 2022-02-21 15:40
![WindowsTerminal_NFdfnfk4FE](https://user-images.githubusercontent.com/30464573/154986735-ec6fa486-61ef-4802-b607-71faca676c96.png)
Version: 3,8.

SDK
![idea64_rjNl4GtuGD](https://user-images.githubusercontent.com/30464573/154988356-84fa6b92-d29a-4583-b5a4-21eac80d8e11.png)

**Comment by FibreFoX** [comment] 2022-02-21 16:22
Sorry, but I need the full Maven output, because I need to know the JDK/JRE path that gets listed. Sometimes there is a problem with the JDK itself (as there are a lot of JDK flavors out there), or the setup of maven itself.
So you are using a bundled version of IntelliJ, is that correct? Can you strip down a minimal project which you can share, where you can reproduce that issue?

**Comment by MrTob** [comment] 2022-02-21 16:31
[hello-javafx-maven-example.zip](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/8110821/hello-javafx-maven-example.zip)
Yes i use InteliJ. This is my Project, it only shows an input field and an button

**Comment by FibreFoX** [comment] 2022-02-21 17:40
Hm, it seems that there is something different broken on you development machine. Running `mvn jfx:native` from the IntelliJ-interface shows me normal behaviour.
InnoSetup (version 5, because later versions are not compatible more with JDK 8 ... at least this is what I recall right now) and WiX Toolset were installed via choco:
```ps
choco install innosetup --version=5.6.1.20190126
choco install wixtoolset
```
I have OpenJDK 8 Update 211 installed and are running IntelliJ IDEA 2021.3.2 with bundled maven. As far as I can tell, one of the installer tools are not set up correctly.
![grafik](https://user-images.githubusercontent.com/1042579/155004321-20b47924-8c46-46a7-b31a-9bcc4539f16b.png)

Maybe you are having InnoSetup 6 installed?

**Comment by MrTob** [comment] 2022-02-21 19:32
Yes Inno Setup Compiler 6.2.0

**Comment by FibreFoX** [comment] 2022-02-21 19:51
Can you try using the 5er version, it that still gives your that error?

**Comment by MrTob** [comment] 2022-02-21 19:58
Yes with the version 5.6.1 i have still the same error

**Comment by FibreFoX** [comment] 2022-02-21 20:39
Okay, there seems to be something with your system setup. Can you check if setting verbose to true gives you more information? 
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.3</version>
                <configuration>
                    <vendor>YourCompany</vendor>
                    <mainClass>com.zenjava.examples.hellojfxmaven.HelloJavaFxAndMavenApp</mainClass>
                    <verbose>true</verbose>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
Normally all available bundlers are executed in a row, so maybe you can find some details when verbose output is printed. Sadly I can not reproduce the problem on my side.

**Comment by MrTob** [comment] 2022-02-22 16:04
i tried it in a virtual maschine with only maven and a jdk + wix toolset + inno setup installed . still the same error! 
i use openjdk version "1.8.0-262"
any other ideas?

**Comment by FibreFoX** [comment] 2022-02-22 17:15
@MrTob please check what using verbose output gives you, it produced more details about what is happening "in the background". And please post the resulting output here, so I can help more (as I am not able to reproduce this).

**Comment by FibreFoX** [comment] 2022-02-22 17:21
Just for my reference: there is an old thread over at stack-overflow with a similar symptom, but not real solution: https://stackoverflow.com/questions/49628163/where-how-to-get-the-msvc-dlls-java-1-8-0-144-wants

**Comment by MrTob** [comment] 2022-02-22 22:03
the argument <verbose>true</verbose> doesn't give any further relevant infomation concerning the problem. a funny piece of information is that in the "target/jfx/Native folder" an .exe file is created which i can execute by double clicking on it. but if i copy the exe to another location it can't be opened anymore. no error is shown in the command line either.
![explorer_Bw8KwzlCAg](https://user-images.githubusercontent.com/30464573/155227121-4c2ecf50-9660-496f-a354-528015deeeb7.png)

**Comment by FibreFoX** [comment] 2022-02-22 22:09
Can you provide the generated log with `verbose` set to true please?
And can you provide a link to what OpenJDK you installed? There seems to be something wrong with the used JDK somehow.

**Comment by MrTob** [comment] 2022-02-23 16:47
im using OpenLogic’s OpenJDK 8u262-b10
this is the output I get with `<verbose>true</verbose>`.

```
[INFO] 
[INFO] ---------------< com.zenjava:hello-javafx-maven-example >---------------
[INFO] Building JavaFX Example Maven Project 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> javafx-maven-plugin:8.8.3:native (default-cli) > :jar @ hello-javafx-maven-example >>>
[INFO] 
[INFO] >>> javafx-maven-plugin:8.8.3:jar (jar) > [jfxjar]package @ hello-javafx-maven-example >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hello-javafx-maven-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hello-javafx-maven-example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hello-javafx-maven-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hello-javafx-maven-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ hello-javafx-maven-example ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hello-javafx-maven-example ---
[INFO] Building jar: C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\hello-javafx-maven-example-1.0-SNAPSHOT.jar
[INFO] 
[INFO] <<< javafx-maven-plugin:8.8.3:jar (jar) < [jfxjar]package @ hello-javafx-maven-example <<<
[INFO] 
[INFO] 
[INFO] --- javafx-maven-plugin:8.8.3:jar (jar) @ hello-javafx-maven-example ---
[INFO] Building JavaFX JAR for application
[WARNING] Skipped checking for packager.jar. Please install at least Java 1.8u40 for using this feature.
[INFO] Adding 'deploy' directory to Mojo classpath: C:\Users\<username>\IdeaProjects\hello-javafx-maven-example/src/main/deploy
[INFO] 
[INFO] <<< javafx-maven-plugin:8.8.3:native (default-cli) < :jar @ hello-javafx-maven-example <<<
[INFO] 
[INFO] 
[INFO] --- javafx-maven-plugin:8.8.3:native (default-cli) @ hello-javafx-maven-example ---
[INFO] Building Native Installers
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\hello-javafx-maven-example-1.0-SNAPSHOT-jfx.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\commons-lang-2.6.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\jcl-over-slf4j-1.6.1.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\log4j-1.2.16.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\miglayout-core-4.2.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\miglayout-javafx-4.2.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\slf4j-api-1.6.1.jar file to application resources.
[INFO] Add C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\app\lib\slf4j-log4j12-1.6.1.jar file to application resources.
Running [C:\Program Files\Java\openlogic-openjdk-8u262-b10-win-64\jre\bin\java, -version]
Creating app bundle: hello-javafx-maven-example-1.0-SNAPSHOT in C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\native
  Using default package resource [application icon]  (add package/windows/hello-javafx-maven-example-1.0-SNAPSHOT.ico to the class path to customize)
Running [C:\Users\<username>\AppData\Local\Temp\iconswap5869556027116526245.exe, C:\Users\<username>\AppData\Local\Temp\fxbundler9178223172474391418\windows\hello-javafx-maven-example-1.0-SNAPSHOT.ico, C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\native\hello-javafx-maven-example-1.0-SNAPSHOT\hello-javafx-maven-example-1.0-SNAPSHOT.exe]
Icon File Name: C:\Users\<username>\AppData\Local\Temp\fxbundler9178223172474391418\windows\hello-javafx-maven-example-1.0-SNAPSHOT.ico
Executable File Name: C:\Users\<username>\IdeaProjects\hello-javafx-maven-example\target\jfx\native\hello-javafx-maven-example-1.0-SNAPSHOT\hello-javafx-maven-example-1.0-SNAPSHOT.exe
  Config files are saved to C:\Users\<username>\AppData\Local\Temp\fxbundler9178223172474391418\windows. Use them to customize package.
```

**Comment by FibreFoX** [comment] 2022-02-23 16:59
Okay, with that JDK I am able to reproduce the issue 🐱

**Comment by FibreFoX** [comment] 2022-02-23 17:06
The issue even exists in the latest version 8u292-b10 of the OpenLogic OpenJDK, no nothing helping there.

**Comment by FibreFoX** [comment] 2022-02-23 17:31
I think I found the cause of the issue, but I think I can not give you a fix for this. (sorry)

The JDK provided by OpenLogic provides a file called `ant-javafx.jar`, where all the system native files are contained (can be found inside the installed JDK in the `lib`-folder). That file is missing the required runtime files, that are required by the launcher. On some systems it does work, because these files seem to be available on a system-level already (thats the reason it did start for you).

Just a side note: the exe-file is not the real application, it is a "starter" executable, which reads its configuration from the filename and expects a certain folder-structure, so nothing wrong it not working when executed in a different location.

Here a screenshot of what it looks like with OracleJDK:
![grafik](https://user-images.githubusercontent.com/1042579/155371274-aa94475c-d7ad-4aa1-8558-105269305b4a.png)

Here a screenshot of what it looks with OpenLogic JDK:
![grafik](https://user-images.githubusercontent.com/1042579/155371730-ee94a5bc-1eec-461e-a4a6-37781c1c259e.png)

As you can see, there are files missing in there, which makes that JDK not equivalent to the OracleJDK sadly.

On maven-plugin level I can not do anything here to fix this, but you might be able to fix that by modifying that JAR-file by adding the missing files. You should be able to find them on your local windows installation at `C:\Windows\System32\vcruntime140.dll` or `C:\Windows\System32\msvcp140.dll`. If these files are missing, you just can download a official runtime installer of these `Visual C++ Redistributable` files here:  
- for 32-bit: https://aka.ms/vs/16/release/vc_redist.x86.exe
- for 64-bit: https://aka.ms/vs/16/release/vc_redist.x64.exe

Another alternative would be to install a different OpenJDK, for example [ojdkbuild](https://github.com/ojdkbuild/ojdkbuild),. Using chocolatey on Windows just makes this a one-liner `choco install ojdkbuild8` and does contain these required files.
![grafik](https://user-images.githubusercontent.com/1042579/155374171-38ba259a-5166-4197-834d-97cfaf7b6c73.png)


I assume there are some legal reasons, of maybe this is just a bug on the OpenLogic-buildserver, not sure.

**Closed as completed by FibreFoX** 2022-02-23 17:31 UTC
Labels: Windows, native launcher, It's the JDK, JDK 8

**Comment by MrTob** [comment] 2022-02-23 17:39
yay, i tried it with the version from oracle. now it works fine
https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
thank you very much for your effort and the quick help
