### ISSUE TITLE
maven fails to build, could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20

### ISSUE THREAD

**Issue by HerbertKoelman** [javafx-maven-plugin/javafx-maven-plugin#311] opened 2017-10-08 13:00 UTC
Hello, maven doesn't seem to find this artifact when building my JavaFX app. 

Is there a fix or work around ?

I'm using:
- command (in bash): mvn clean install
- mac os X: high sierra 10.3
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```
- maven: 3.5.0
```
Maven home: /Users/herbert/maven/3.5.0
Java version: 9, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.13", arch: "x86_64", family: "mac"
```
- maven error message
```
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:build-jar (create-jfxjar) on project FuzzFX: Execution create-jfxjar of goal com.zenjava:javafx-maven-plugin:8.8.3:build-jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/../lib/ant-javafx.jar -> [Help 1]
```
- related pom.xml
[pom.xml.zip](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/1366883/pom.xml.zip)

**Comment by FibreFoX** [comment] 2017-10-08 13:11
The plugin currently does not support JDK9, so this gets closed as duplicate of #287

**Closed by FibreFoX** 2017-10-08 13:11 UTC

**Comment by HerbertKoelman** [comment] 2017-10-08 13:22
Ok, does it support maven's toolchain feature ? I understand that toolchain can let set the JDK toolset version I want maven to use when building things. Do you know if my understanding is correct ?

Maven plugins are all using the required toolchain 
```
[INFO] Required toolchain: jdk [ vendor='oracle' version='1.8' ]
```
But it seems that javafx bundler package is search for features in the jdk9 directory and not the one that was referenced in the toolcahin setting.

I've set the toolchain back to 1.8, I end up with the same error message.
```
Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/../lib/ant-javafx.jar
```

```
mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Fuzz (JavaFX) 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ FuzzFX ---
[INFO] Deleting /Users/herbert/Documents/Java/FuzzFX/target
[INFO] 
[INFO] --- maven-toolchains-plugin:1.1:toolchain (default) @ FuzzFX ---
[INFO] Required toolchain: jdk [ vendor='oracle' version='1.8' ]
[INFO] Found matching toolchain for type jdk: JDK[/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home]
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ FuzzFX ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 28 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ FuzzFX ---
[INFO] Toolchain in maven-compiler-plugin: JDK[/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 25 source files to /Users/herbert/Documents/Java/FuzzFX/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ FuzzFX ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/herbert/Documents/Java/FuzzFX/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ FuzzFX ---
[INFO] Toolchain in maven-compiler-plugin: JDK[/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/herbert/Documents/Java/FuzzFX/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ FuzzFX ---
[INFO] Toolchain in surefire-plugin: JDK[/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home]
[INFO] Surefire report directory: /Users/herbert/Documents/Java/FuzzFX/target/surefire-reports
```

**Comment by HerbertKoelman** [comment] 2017-10-08 13:25
For your information, this command fixed the issue.

`JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home mvn clean install`

It indeed looks like the javafx packager is not using the currently selected toolchain to build.

:-)

**Comment by FibreFoX** [comment] 2017-10-08 13:26
With JDK8 there was that `ant-javafx.jar`-file which contains the classes use for bundling, with JDK9 these classes were shifted to `jdk.packager.jmod`. The problem is to have both worlds combined. This plugin does NOT work with the toolchain-plugin (every plugin has to implement this in addition).

A workaround for supporting this has to be by creating own classloaders and such nasty things :(

**Comment by HerbertKoelman** [comment] 2017-10-08 13:34
Make sense.

I'm VERY happy with your work. Any idea of when you'll consider release a java version 9 support ?

**Comment by FibreFoX** [comment] 2017-10-08 13:41
Sadly no, private life is tricky currently, and my Mac-bundler workaround does not work anymore with jdk9 (because the methods of the used internal classes have changed too heavily), compatibility for jdk8 and jdk9 with the same plugin is more than trivial (especially with the new `module-info.java`-class crap, and in addition some code-cleanup ... too much work to cover, so no ETA for this, but as I'm getting progress on this slowly, 2017 will be a target I don't want to miss.

Is there anything special you are using from JDK 9?

**Comment by HerbertKoelman** [comment] 2017-10-08 13:48
I'm not looking for something special in the JDK 9, but it seems that some fixes for JavaFX 9 are bundled in this JDK release.
So I thought the easiest way to move and to see if these fixes were of some importance to my work was to upgrade the JDK. I wrongly thought that downgrading was as easy as setting the tool chain back to JDK 1.8 8-)
