### ISSUE TITLE
Native package for Ubuntu doesn't work

### ISSUE THREAD

**Issue by malafeev** [javafx-maven-plugin/javafx-maven-plugin#124] opened 2015-05-25 19:59 UTC
I built native package on Ubuntu using 
```
mvn clean fx:native
```

But when I execute bundle I get error:
```
client-1.1 No main class specified
client-1.1 Failed to launch JVM
```

My pom.xml contains:

```
<plugin>
   <groupId>com.zenjava</groupId>
   <artifactId>javafx-maven-plugin</artifactId>
   <version>8.1.2</version>
   <configuration>
       <mainClass>com.client.ui.Main</mainClass>
   </configuration>
</plugin>
```

**Comment by FibreFoX** [comment] 2015-05-26 07:55
Can you provide a sample-project?
By the way: please use ```mvn jfx:native```

**Comment by maxd** [comment] 2015-05-26 09:17
+ required full log of `mvn clean fx:native`. Seems like this is problem related to Maven configuration.

**Comment by malafeev** [comment] 2015-05-26 09:20
Misprint: I used  `jfx:native` goal

**Comment by maxd** [comment] 2015-05-26 09:29
We get it, but this is don't cause your error.

**Comment by FibreFoX** [comment] 2015-05-26 10:13
Just for being curious: do you execute the generated ´´´.jar´´´ or the generated ´´´-jfx.jar´´´ ? As far as i can see, this is no bug of javafx-maven-plugin. Please reopen this issue with more details, I will close this as invalid until then.

**Comment by stelfrich** [comment] 2015-09-22 12:27
@FibreFoX @maxd: I think, I have a similar / the same issue with the native launcher on Ubuntu 12.04.

The build process doesn't show any errors, deb and rpms are built correctly. I can execute the `*-jfx.jar` using `java -jar vizardous-1.2.1-SNAPSHOT-jfx.jar` without any problems because the main class is properly set in the `*-jfx.jar`. However, executing the launcher shows the following error on stdout:

    vizardous-1.2.1-SNAPSHOT No main class specified
    vizardous-1.2.1-SNAPSHOT Failed to launch JVM

I am running Java(TM) SE Runtime Environment (build 1.8.0_60-b27) on Ubuntu 12.04.5. javafx-maven-plugin is at 8.1.4. The Maven logfile is at https://gist.github.com/stelfrich/039c491a4ef02bd8739a#file-maven-log. The POM at https://gist.github.com/stelfrich/c9a0160781b73a30d3fd#file-pom-xml.

**Comment by FibreFoX** [comment] 2015-09-22 12:38
@stelfrich Do you have the possability to create a small project, where we can check this? I would create a dedicated VM with ubuntu to analyse this.

**Comment by FibreFoX** [comment] 2015-09-22 12:41
@stelfrich Which OS are you running? 32bit or 64bit?

**Comment by stelfrich** [comment] 2015-09-22 12:41
@FibreFoX: 64bit

**Comment by FibreFoX** [comment] 2015-09-22 12:42
@stelfrich okay, please create a simple project, I will get back to you after some research, should not be longer than the next two days

**Comment by Jerady** [comment] 2015-09-22 12:44
I am facing the same problems since quite a while: "No main class specified".

The app is also launching via "java -jar" and I can see the Main-Class entry in META-INF/MANIFEST.MF points to the right Class (Main-Class: de.jensd.mqttfx.ui.Run) (Ubuntu 14.04 32Bit and 64Bit).

**Comment by FibreFoX** [comment] 2015-09-22 12:51
Did you try this with a previous version of java (loke 1.8.0-25 or 1.8.0-40)? Maybe it's something they've changed in their native launcher.

**Comment by stelfrich** [comment] 2015-09-22 12:52
@FibreFoX: MWE at https://github.com/stelfrich/javafx-native-mwe

**Comment by FibreFoX** [comment] 2015-09-22 12:54
@stelfrich thanks a lot, just to make sure: have you checked, if that project still contains that bug?

**Comment by stelfrich** [comment] 2015-09-22 12:59
@FibreFoX: In my current configuration. The error persists. I have a meeting now and will check an older JDK (1.8.0u40) afterwards..

**Comment by Jerady** [comment] 2015-09-22 13:00
I think it happened since the change from 1.8.0u20 to 1.8.0u40.

**Comment by stelfrich** [comment] 2015-09-22 14:16
I can confirm @Jerady's observation. With 1.8.0u20, 1.8.0u25, and 1.8.0u31 the MWE works fine. The main class is not found (https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/124#issuecomment-142272760) starting with 1.8.0u40..

**Comment by Jerady** [comment] 2015-09-23 09:51
any new insights so far?

**Comment by FibreFoX** [comment] 2015-09-23 11:49
@Jerady feel free to contribute by creating pull-requests.Currently it seems that they switched from C to C++ which might result in different behaviour, but i will need a bit time to create and compile my own launcher which re-created these scenarios. As this is a project I'm not getting paid for, this might take it's time, so please have patience ;)

**Comment by Jerady** [comment] 2015-09-23 11:53
Sure! I was just curious if there is any progress ;-). Clearly you have to take your time! I very much appreciate your efforts, thanks a lot!

**Comment by FibreFoX** [comment] 2015-09-23 11:55
As the launcher not being that big, maybe the problem resides inside their used technique to find current path: `/proc/self/exe`

Should be not as hard to check this :) I will report as soon as I find something new here, and if so, I will be report this to the JavaFX-team.

**Comment by FibreFoX** [comment] 2015-09-23 14:09
I can confirm the wrong behaviour running Ubuntu 14.04 LTS with oracle-java 1.8.0_60-b27 running in 64bit (within Virtualbox 5.0).

I got this while building, maybe this will give me a clue where to search deeper (in the case it isn't the launcher):
```
The jar lib/xalan-2.6.0.jar has a main class org.apache.xalan.xslt.Process that does not match the declared main vizardous.Vizardous
The jar lib/omero-client-5.0.0-beta1-256-019d14a-ice34-b3523.jar has a main class  that does not match the declared main vizardous.Vizardous
The jar lib/jxl-2.6.12.jar has a main class jxl.demo.Demo that does not match the declared main vizardous.Vizardous
```

I'm still analyzing this ;) and dropping my findings here as a nice way to annoy you :smile:

**Comment by Jerady** [comment] 2015-09-23 14:11
Great! Go ahead ;-)!

**Comment by FibreFoX** [comment] 2015-09-23 14:15
The message appears, because this is not equal ...
https://github.com/Debian/openjfx/blob/585900f340aaa1513b6ef998b1be5023f4eed9f9/modules/fxpackager/src/main/java/com/oracle/tools/packager/StandardBundlerParam.java#L609

Will seach deeper (maybe we have to fill just another field?)

**Comment by FibreFoX** [comment] 2015-09-23 14:39
This is the line, I have to check, why it's failing:
https://github.com/Debian/openjfx/blob/585900f340aaa1513b6ef998b1be5023f4eed9f9/modules/fxpackager/src/main/java/com/oracle/tools/packager/StandardBundlerParam.java#L611

the other line is for legacy-manifest-attributes, as far as I understood
http://mail.openjdk.java.net/pipermail/core-libs-dev/2012-November/012382.html

**Comment by FibreFoX** [comment] 2015-09-23 15:25
The errors are misleading, because all JARs are scanned for a main-method ...

I tried it with my own project (private one, sry), but there it worked flawlessly ... maybe it's when having more than one main-method?! I'll try to strip down the project from @stelfrich ... maybe it's a conflict with one of these jars.

**Comment by FibreFoX** [comment] 2015-09-23 15:57
@Jerady  @stelfrich 
I realized something today *turns-on-southpark-music*:
The main-class of the project is no javafx-application ;) having a main-method is not sufficient, but thats not the source of the problem.

The crazy part I found out: please change the configuration-parameter `appName` to something simpler, like this `<appName>iAmWorking</appName>`.

I think it has something todo with the way /proc/self/exe handles the folder ... haven't tested it yet, but that is the next step I'm confronted with (before I'm contacting the javafx-guys).

**Comment by FibreFoX** [comment] 2015-09-23 16:14
hm .... `/proc/self/exe` seems to work normal, ... I think I'll have to create a bug-ticket at the oracle-JIRA.

**Comment by stelfrich** [comment] 2015-09-23 16:16
Woooot? Could you hear my jaw dropping? The simpler appName fixes the problem in the main project..

**Comment by stelfrich** [comment] 2015-09-23 16:18
The question remains: how simple is simple? No dashes in the `appName`? Have you gained any insights on that @FibreFoX?

**Comment by FibreFoX** [comment] 2015-09-23 16:40
Nope, I'm still working on it, but it takes some time, because I'm "working" mobile now ;) I'll get back with more informationen in some hours.

**Comment by FibreFoX** [comment] 2015-09-23 17:09
Okay, I've finished my investigation, it has to do something with the DOT within the filename, it seems that the `.cfg`-file is not found by the `libpackager.so` (aka the loading library).

To make it clear to everyone else: IT'S NOT A BUG OF JAVAFX-MAVEN-PLUGIN, it's inside the JDK.

**Comment by Jerady** [comment] 2015-09-23 17:59
Brat mir einer 'nen Storch! That's it! Thank you so much for investigation!
Until this issue is fixed in the JDK its ok to remove the "." in MQTT.fx ;-)

**Comment by FibreFoX** [comment] 2015-09-23 18:01
After further investigation, i can confirm this bug even more and it seems something broken within getting the proper filename, reproduced with this:
* generating project with simple appName `iAmWorking`
* renamig generated launcher to something like `iAmNot.Working`
* launching application will fail
* renaming generated `.cfg`-file to `iAmNot.cfg`
* launching application succeeds

It's something inside libpackager.so
https://github.com/Debian/openjfx/blob/585900f340aaa1513b6ef998b1be5023f4eed9f9/modules/fxpackager/src/main/native/library/common/Package.cpp#L58

I suspect the algorithm to find the filename is wrong, it's looking for "the last dot":
https://github.com/Debian/openjfx/blob/585900f340aaa1513b6ef998b1be5023f4eed9f9/modules/fxpackager/src/main/native/library/common/FilePath.cpp#L149

@Jerady @stelfrich If someone of you two knows how to contact oracle about this ... javafx-jira isn't working anymore

**Comment by FibreFoX** [comment] 2015-09-23 18:13
@Jerady I took a peak into mqtt.fx, and a lot of ubuntu-bugs should get closed after this finally being fixed, something like this: https://bitbucket.org/Jerady/mqtt-fx-client/issues/40/ubuntu-1404-launcher-is-not-working

**Comment by Jerady** [comment] 2015-09-23 18:57
Indeed, that's why I am so happy its "fixed". Some people waiting for this since month!
I know some guys at Oracle to file this bug but I guess since they handed all over to openjfx Oracle will not take action here. "OSS so fix your own". Anyway I will get in touch with them.

**Comment by FibreFoX** [comment] 2015-09-23 19:24
@Jerady thanks a lot, would really help :) i felt a bit guilty not being able to help you when you e-mailed me, but finally we nailed this nasty piece down to the JDK itself :smile:

In the meantime, i will consider working on a workaround (by renaming that `.cfg`-file ... just have to look for the correct time within the build-phase).

**Comment by FibreFoX** [comment] 2015-09-23 19:35
Thats funny:
https://wiki.openjdk.java.net/display/OpenJFX/Submitting+a+Bug+Report
```
JavaFX bugs are now part of the JDK Bug System (JBS) hosted at https://bugs.openjdk.java.net/.
```

**Comment by Jerady** [comment] 2015-09-23 20:12
See! Oracle handed all over!

**Comment by FibreFoX** [comment] 2015-09-23 21:12
@Jerady  @stelfrich 
I have pushed a SNAPSHOT-version which renames the created `.cfg`-file for linux-launcher, could you give it a try?

Please add this to your pom.xml
```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

And make sure to use version `8.1.5-SNAPSHOT`

**Comment by FibreFoX** [comment] 2015-09-23 21:33
The workaround makes it possible to leave your projects unchanged, just having a "wrong name" of the metadata shouldn't destroy your applications ;)

**Comment by stelfrich** [comment] 2015-09-24 05:52
@FibreFoX: Thanks for the quick fix! I can confirm, that the SNAPSHOT version fixes the problem, although I don't completely understand why: the name of the generated config is in my case `vizardous-1.2.cfg`..

**Comment by FibreFoX** [comment] 2015-09-24 06:58
@stelfrich it is very simple, let me explain it to you:

Platform "Windows":
* generated launcher: `i-am.working.exe`
* launcher-algorithm extracts the extension and now searches for **`i-am.working`**`.cfg`

Platform "Linux":
* generated launcher: `i-am.working.1.2.0-SNAPSHOT`
* launcher-algorithm extracts the "extension" (a concept not known in linux-space for executables) and now searches for **`i-am.working.1.2`**`.cfg`

And this is where my workaround comes to play :smile:

**Comment by Jerady** [comment] 2015-09-24 07:05
#Works! 
Again: thanks a lot for your effort! 
8.1.5 should be released soon ;-)

**Comment by FibreFoX** [comment] 2015-09-24 07:10
@Jerady  @stelfrich  @malafeev 
I am working on this and will release a new version today, so if everything works, you should be able to use the new 8.1.5-release tonight/tomorrow. Still have to do some work on disabling this feature, and creating a new IT-project for linux-systems only.

**Comment by Jerady** [comment] 2015-09-24 07:13
Awesome!

**Comment by stelfrich** [comment] 2015-09-24 08:03
Nice! :+1:

**Comment by FibreFoX** [comment] 2015-09-24 09:15
IT-projects and disable-flag are merged, I will close this issue when new version got uploaded to Sonatype

**Comment by FibreFoX** [comment] 2015-09-24 09:27
New version got released on sonatype, it's just a matter of hours to be propagated to maven-central (as always/normal).

**Closed by FibreFoX** 2015-09-24 09:27 UTC
Labels: Linux, native launcher

**Comment by FibreFoX** [comment] 2015-09-24 12:08
just filed a bug at oracle  ... let us see where this ends :smile:

**Comment by Jerady** [comment] 2015-09-24 12:09
I bet they will reject it with the "openjdk" hint!

**Comment by FibreFoX** [comment] 2015-09-24 12:10
The good part: it's the packager, which isn't just a javafx-part anymore. Even the filename was renamed from "javafxpackager" to "javapackager" :D

**Comment by Jerady** [comment] 2015-09-24 12:11
true. lets sit and wait. At least you provides a solution for the rest of us ;-)

**Comment by FibreFoX** [comment] 2015-09-24 20:14
https://bugs.openjdk.java.net/browse/JDK-8137114
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8137114

**Comment by totalvoidness** [comment] 2015-10-22 20:07
Has anyone tried creating a .deb bundle using the OpenJDK? I stumbled upon this thread, as I have the exact same error: (No main class specified, Failed to launch JVM). But I _only_ experience this error with the OpenJDK (8u66). With Oracle JDK (8u60) everything works like a charm. Also execution via `java -jar ...` is not a problem in either case.

To be honest I don't use this javafx-maven-plugin (yet :wink:), thus I don't want you to reopen this issue, but maybe someone can give me a hint on whats wrong. In both cases (Oracle and OpenJDK) my .cfg file as well as the binary do *not* contain any ".".

The directory structure is the same for both JDKs. But the binary and the cfg-file (as well as the embedded JVM, obviously) differ.

![directory-structure](https://cloud.githubusercontent.com/assets/1204330/10676619/c0d42916-7907-11e5-9400-f1577daef216.png)

Any hint is appreciated, as I want to switch from embedding the Oracle JVM to the OpenJDK for legal reasons as well easier distribution.

**Comment by FibreFoX** [comment] 2015-10-22 20:32
Hi @totalvoidness, just to be clear: I just can check such issues when application was bundled via javafx-maven-plugin. Support for normal ANT-version has to come from Oracle themselves or could be found at some places. The issues here should only be on topic of javafx-maven-plugin.

But back to your question/problem: have you checked inside `Cryptomator.cfg` if the referenced JAR is the right one? For better debugging you should try to create a project, where this kind of issue can be reproduced.

**Comment by totalvoidness** [comment] 2015-10-23 17:54
@FibreFoX I'm currently testing this. But have to do a dist-upgrade first, as ubuntu utopic isn't supported any more. As far as I can tell now: Oracle JDK 8u45, which is the last version for utopic in webupd8 ppa, does not work neither with nor without the `skipNativeLauncherWorkaround124`. But I think thats ok, as any native package will most likely contain the latest JDK anyway. I'll report about Oracle 8u66 as well as OpenJDK as soon as my VM is up-to-date.

**Comment by FibreFoX** [comment] 2017-07-05 07:37
As I'm contacted by some oracle guy, this is for my own reference/documentation:
https://github.com/teamfx/openjfx-9-dev-rt/blob/2b5bdc2706c51ee57c65f1d93246252a6bd30834/modules/jdk.packager/src/main/native/library/common/GenericPlatform.cpp#L154

```cpp
#if defined(WINDOWS) || defined(LINUX)
TString GenericPlatform::GetAppName() {
    TString result = GetModuleFileName();
    result = FilePath::ExtractFileName(result);
    result = FilePath::ChangeFileExt(result, _T(""));
    return result;
}
#endif //WINDOWS || LINUX
```

On Windows- AND Linux-systems the extension gets removed, which breaks the gathered appName on linux when having multiple DOTS inside the filename. This happens when the cpp-class Package gets initialized: https://github.com/teamfx/openjfx-9-dev-rt/blob/2b5bdc2706c51ee57c65f1d93246252a6bd30834/modules/jdk.packager/src/main/native/library/common/Package.cpp#L78
