### ISSUE TITLE
DMG file is not produced / errors out when running maven over SSH

### ISSUE THREAD

**Issue by aaronjrich** [javafx-maven-plugin/javafx-maven-plugin#316] opened 2017-10-26 16:00 UTC
Hi,

We have a maven build that is correctly producing an .app, .dmg and .pkg native output on a Mac for our JavaFX application.  The next step for us was to automate this and we've started with the thoughts of using SSH, SCP to that or another Mac.  When doing that, or running the maven command with PLINK, the dmg output is erring with the following (however the .app and .pkg appears to be fine):
```
Running [osascript, /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler8780709063454013570/macosx/App-dmg-setup.scpt]
/var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler8780709063454013570/macosx/App-dmg-setup.scpt:64:68: execution error: An error of type -10810 has occurred. (-10810)
java.io.IOException: Exec failed with code 1 command [[osascript, /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler8780709063454013570/macosx/App-dmg-setup.scpt] in unspecified directory
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
        at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:375)
        at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:92)
        at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:549)
        at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:623)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Any help with this would be appreciated.

**Comment by FibreFoX** [comment] 2017-10-26 16:28
Which OracleJDK are you using, and which MacOS-version?

**Comment by aaronjrich** [comment] 2017-10-26 17:34
We're using jdk1.8.0_144.jdk on a Mac mini (Late 2012) running OS X Yosemite 10.10.5.

**Comment by aaronjrich** [comment] 2017-10-27 17:50
Ran it again today using plink command and got this:

Preparing dmg setup: /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler1
034976772515631899/macosx/App-dmg-setup.scpt
  Using default package resource [DMG setup script]  (add package/macosx/Transit
ionsDataTool-dmg-setup.scpt to the class path to customize)
 Creating DMG file: /Users/bestpractices/temp/Transitions JavaFX New FA/target/j
fx/native/App-1.0.dmg
Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/h3/rt27qk510
2l0q21s_9wd_nwm0000gn/T/fxbundler1034976772515631899/images/image-58595968154858
91485, -volname, TransitionsDataTool, -ov, /var/folders/h3/rt27qk5102l0q21s_9wd_
nwm0000gn/T/fxbundler1034976772515631899/images/App-tmp.dmg, -fo
rmat, UDRW]
Running [/usr/bin/hdiutil, attach, /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000g
n/T/fxbundler1034976772515631899/images/TransitionsDataTool-tmp.dmg, -quiet, -mo
untroot, /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler1034976772515
631899/images]
Running [osascript, /var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler10
34976772515631899/macosx/App-dmg-setup.scpt]
_RegisterApplication(), FAILED TO establish the default connection to the Window
Server, _CGSDefaultConnection() is NULL.
/var/folders/h3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler1034976772515631899/ma
cosx/App-dmg-setup.scpt:64:68: execution error: Finder got an error: Application isnΓÇÖt running. (-600)
java.io.IOException: Exec failed with code 1 command [[osascript, /var/folders/h
3/rt27qk5102l0q21s_9wd_nwm0000gn/T/fxbundler1034976772515631899/macosx/Transitio
App-dmg-setup.scpt] in unspecified directory
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
        at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
        at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.ja

**Comment by FibreFoX** [comment] 2018-01-04 15:40
@aaronjrich Did you get some time to dig into this any further?

**Comment by aaronjrich** [comment] 2018-01-04 22:16
I haven’t.  I’ve since abandoned the dmg and am just using the .app folder that’s produced instead.

**Comment by FibreFoX** [comment] 2018-01-05 00:11
Hm ... okay, I will close this issue then, because I can't reproduce this. If you happen to get more information, just add this here and I will re-open this. Thanks.

**Closed by FibreFoX** 2018-01-05 00:11 UTC
Labels: JDK 8, Mac, needs investigation

**Comment by francesco-kriegel** [comment] 2018-03-23 14:41
I was facing the same problem when setting up a Jenkins instance on macOS which automatically creates bundles of my piece of software.  In my case, this problem is caused by the necessity of `osascript` to interact with a user, cf. the thrown error number `-610` and [http://www.cs.cmu.edu/afs/cs/user/lenzo/html/mac_errors.html](http://www.cs.cmu.edu/afs/cs/user/lenzo/html/mac_errors.html).  Jenkins runs as a user `jenkins` which is a dedicated user only for running Jenkins---in particular, this user does not start a window manager.  In my case, there are at least two solutions.  Either change the user under which Jenkins and thus also the `mvn` process generating the bundles shall be executed to the user one is usually logged on as, or add the flag `<mac.dmg.simple>true</mac.dmg.simple>` to the `<bundleArguments>` in `pom.xml`.  See also [https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacDmgBundler.java#L366](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacDmgBundler.java#L366) which corresponds to the line at which @aaronjrich's and my `mvn` process throws a `java.io.IOException`.  Simply setting `<mac.dmg.simple>true</mac.dmg.simple>` is easy and straight-forward, and the only disadvantage I could see is that the background image is not set in the DMG.

Some more background information as follows.  Setting `<buildRoot>` in `<bundleArguments>` to some fixed directory, e.g., setting `<buildRoot>target/jfx/buildRoot</buildRoot>`, allows to copy the AppleScript that is created during the bundling of the DMG file and ensures the correct display of the DMG file when opened.  In my case, it has filename `Concept Explorer FX-dmg-setup.scpt` and looks as follows.

```
tell application "Finder"
  tell disk "Concept Explorer FX"
    open
    set current view of container window to icon view
    set toolbar visible of container window to false
    set statusbar visible of container window to false

    -- size of window should match size of background
    set the bounds of container window to {400, 100, 917, 370}

    set theViewOptions to the icon view options of container window
    set arrangement of theViewOptions to not arranged
    set icon size of theViewOptions to 128
    set background picture of theViewOptions to file ".background:background.png"

    -- Create alias for install location
    make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}

    set allTheFiles to the name of every item of container window
    repeat with theFile in allTheFiles
      set theFilePath to POSIX Path of theFile
      if theFilePath is "/Concept Explorer FX.app"
        -- Position application location
        set position of item theFile of container window to {120, 135}
      else if theFilePath is "/Applications"
        -- Position install location
        set position of item theFile of container window to {390, 135}
      else
        -- Move all other files far enough to be not visible if user has "show hidden files" option set
        set position of item theFile of container window to {1000, 0}
      end
    end repeat

    close
    open
    update without registering applications
    delay 5
  end tell
end tell
```

However, when `osascript` is called to execute this script, then it tries to open the so far created DMG image in order to commit further changes.  I claim that if no window manager for the executing user is present, then this fails.

Perhaps it would be helpful to create a bug ticket for the maintainers of the DMGBundler.
