### ISSUE TITLE
Error executing native linux launcher

### ISSUE THREAD

**Issue by ST-DDT** [javafx-maven-plugin/javafx-maven-plugin#222] opened 2016-08-05 09:36 UTC
When I create a simple project that only consists of the pom (and the target/classes folder)
(This of course effects complex projects as well)
````xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.example</groupId>
	<artifactId>FakeProject</artifactId>
	<version>1.0.0</version>

	<build>
		<plugins>
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.5.0</version>
				<configuration>
					<appName>${project.name}</appName>
					<mainClass>de.does.not.Exist</mainClass>
					<vendor>Example</vendor>
					<bundleArguments>
						<runtime />
					</bundleArguments>
					<jfxMainAppJarName>${project.build.finalName}.jar</jfxMainAppJarName>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
````
(No JRE should be bundled)

And build that project using `mvn jfx:native`.
The build will be successful, but if I try to execute the generated file using 
`./target/jfx/native/FakeProject/FakeProject `:

````
FakeProject Failed to locate JNI_CreateJavaVM
FakeProject Failed to launch JVM
````
Or is that file not supposed to be executed in the first place?

I'm not sure whether this helps pointing out the issue:

`target/jfx/native/FakeProject/app/FakeProject.cfg`
````
app.runtime=
app.mainjar=FakeProject-1.0.0.jar
app.version=1.0
app.mainclass=de/does/not/Exist
app.classpath=
app.preferences.id=de/does/not
app.identifier=de.does.not
````

Running the jar directly works as expected 
(`java -jar target/jfx/app/FakeProject-1.0.0.jar`).

My system setup:
**OS:**
````
Ubuntu 14.04 LTS (64bti)
````

**Java:**
````
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
````

**Maven:**
````
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/example/Apps/apache-maven-3.3.9
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-79-generic", arch: "amd64", family: "unix"
````

This bug occurs also on Java 1.8.0_91-b14.

Maybe this issue is related: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/167

**Comment by FibreFoX** [comment] 2016-08-05 16:21
As the native launcher is part of the JDK, how does this have anything to do with the javafx-maven-plugin? ;)

**Please make sure to provide some project where the bug is reproducable.** And please make sure you are running maven not inside some IDE, because the IDE might change the used JDK-version.

**Comment by FibreFoX** [comment] 2016-08-05 16:21
One thin you might have to check: is JAVA_HOME set up properly? What happens when you do bundle the JRE?

**Comment by ST-DDT** [comment] 2016-08-05 16:35
> As the native launcher is part of the JDK, how does this have anything to do with the javafx-maven-plugin?

I'm using your plugin, so my first assumption is, that I did something wrong configuring the plugin. But since the build is successful but the result does not work, i assume that your plugin did not setup something or did not complain about a missing/wrong value.

> Please make sure to provide some project where the bug is reproducable.

The pom is all you need to be able to reproduce it. (At least on my end.)
Maybe you have to create a fake class so the `target/classes` folder gets created.

> One thin you might have to check: is JAVA_HOME set up properly? 

Yes. This was my first guess, so I ensured that it was set. (Pointing to a jdk)
`/usr/lib/jvm/java-8-oracle`
I haven't tested pointing to the jdk's jre directly (`/usr/lib/jvm/java-8-oracle/jre`).
I will test that in a few days, when I'm back.
I hope I can reproduce this bug on a different client this weekend.

> What happens when you do bundle the JRE?

IIRC this worked, but I cannot test it for a few days.

**Comment by FibreFoX** [comment] 2016-08-05 16:36
I just checked the native source of the launcher: please make sure to have `JRE_HOME` set on the shell environment (not JAVA_HOME).

**Comment by ST-DDT** [comment] 2016-08-05 16:38
> I just checked the native source of the launcher: please make sure to have `JRE_HOME` set on the shell environment (not JAVA_HOME).

I willl try that. Can you emit a warning or something if that value is not set? (Or maybe set it if the value can be guessed.)

**Comment by FibreFoX** [comment] 2016-08-05 16:53
No, because this depends on the system you are running your generated application. The native launcher comes from the JDK, with the javafx-maven-plugin nothing will be generated. It's just a nice wrapper around the existing toolset (javapackager).

To document the location of the environment-variable:
https://github.com/teamfx/openjfx-8u-dev-rt/blob/27362c4a0989088029f9657d5a88658118d8f6ab/modules/fxpackager/src/main/native/library/common/LinuxPlatform.cpp#L157

This will be closed as invalid, please re-open when you found out more which might really be some bug.

**Closed by FibreFoX** 2016-08-05 16:53 UTC
Labels: Linux, native launcher

**Comment by ST-DDT** [comment] 2016-08-08 16:47
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8163356
