### ISSUE TITLE
Maven Parent Project

### ISSUE THREAD

**Issue by hMounir** [javafx-maven-plugin/javafx-maven-plugin#146] opened 2015-09-04 23:15 UTC
Hello, 
I have a problem regarding on how to use the plugin, I have a maven project with two modules, one that contains the main class, and the other module contains the project code itself,

here's my Parent Pom:-

    <modelVersion>4.0.0</modelVersion>
    <groupId>sampleParent</groupId>
    <artifactId>sampleParent</artifactId>
    <packaging>pom</packaging>
    <version>0.1</version>
    <modules>
        <module>mainModule1</module>
        <module>codeModule2</module>
    </modules>

mainModule1 Pom:

      <parent>
        <artifactId>sampleParent</artifactId>
        <groupId>sampleParent</groupId>
        <version>0.1</version>
      </parent>
      <modelVersion>4.0.0</modelVersion>
      <artifactId>mainModule1</artifactId>
      <dependencies>
        <dependency>
            <groupId>sampleParent</groupId>
            <artifactId>codeModule2</artifactId>
            <version>0.1</version>
        </dependency>
      </dependencies>

codeModule2 Pom:

    <parent>
        <artifactId>sampleParent</artifactId>
        <groupId>sampleParent</groupId>
        <version>0.1</version>
    </parent>
    <artifactId>codeModule2 </artifactId>
    <packaging>jar</packaging>

do I add the plugin in the parent pom or in the mainModule pom ?

**Comment by FibreFoX** [comment] 2015-09-06 11:57
Parent-pom does not produce any jar-file, this plugin only works on jar-producing projects. duplicate of this: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/137

**Closed by FibreFoX** 2015-09-06 11:57 UTC
