### ISSUE TITLE
All the .icns (icon files) placed in deploy/package/macosx are not picked up by the JAVAFX Maven Plugin to place them automattically in Resources folder of the main app bundle (OSX)

### ISSUE THREAD

**Issue by yuktikapahwa** [javafx-maven-plugin/javafx-maven-plugin#236] opened 2016-09-19 20:43 UTC
The .icns files places in the deploy/package/macosx folder is giving issues. Only the main bundle icons file is picked up by the maven plugin .
If I try to place the icns files related to the file icon and place them here , they are not picked up automatically by the javafx maven plugin . Hence i have to write a separate script to place the remaining icns images into the Resources folder of the app after it is build.These should also be picked up automatically.

**Comment by FibreFoX** [comment] 2016-09-20 09:49
Hi @yuktikapahwa , thanks for opening this issue.

If I understand you correctly, you have put some ICNS-file into `src/main/deploy/package/macosx` and it is not getting used? Have you checked that the filename is corresponding to the specifiec `<appName>`? Please try to run your bundler with `<verbose>true</verbose>` because the bundler will tell you more about ressource-replacement.

Is it possible to attache some small recreating project to this issue?

**Comment by yuktikapahwa** [comment] 2016-09-20 15:56
Hi , 
Thankyou for your reply. Yes you understood the problem partially correct. I understand that the file name has to be the same as the bundle app name and I am doing that .The name of my file is abc.icns and app name is abc . That gets picked up perfectly fine and placed inside the Resources folder automatically. But i am talking about other icons .What if i need more icons in my Resources folder. I tried placing them in deploy/package/macosx folder but they were not picked up during the build process. I dont have separate app names for each of the icons .App name should be unique and that will be just one and the related icns will be taken from there. But what about the remaining icns files?
I hope you understand my problem now!

**Comment by FibreFoX** [comment] 2016-09-20 16:04
Okay, I think I understand more clearly now. The ICNS-file for your application is getting taken while the bundling-process :) so this is not bug or regression at least.

Any other file put into `<additionalAppResources>` should be the right place for this, as the `src/main/deploy/package/macosx`-folder is ONLY ment for OVERRIDING files, not "new" ones. Thats why I added `<additionalAppResources>` in the first place.

Could you restructure your application a bit maybe, by adjusting the ICNS-location to the addtional folder?

**Comment by yuktikapahwa** [comment] 2016-09-20 16:25
This is not in my hands . All the applications (.app) in the MAC OSX operating system works in such a way that any .icns files it will pick only and only from the Resources folder. If you have a Mac right now , go to the /Applications folder and right click on any .app to check its contents . And when you will check the resources folder , you will find hundreds of .icns files lying there. So that is the thing .The.icns files needs to be placed automatically there.

**Comment by FibreFoX** [comment] 2016-09-20 16:36
Sorry, no Mac-system here ;) no-one has sent me one as a gift yet.

One solution might be to re-implement the native bundler yourself and just override the "doBundle"-method. It sounds to me, that your request is kinda a new feature currently not being possible with the underlying `javapackager`-ant-libs.

**Comment by FibreFoX** [comment] 2016-09-20 16:40
Please don't get confused, I will close this issue, because it has the same root as #235 regarding putting some files into the "whole bundle". As the ICNS-files are being picked up, this issue is no bug.

**Closed by FibreFoX** 2016-09-20 16:40 UTC
Labels: It's the JDK, Mac, question

**Comment by yuktikapahwa** [comment] 2016-09-20 16:51
I understand that . No a problem . But just to confirm , so this problem doesnt have a workaround right now ? Because only one icns is getting picked up and placed in the Resources folder currently . Not all of them . So I feel , this is a bug in the build process as per the requirement of Mac OSX

**Comment by FibreFoX** [comment] 2016-09-20 17:40
The concept of the bundler is, that you can "override" default-files, which includes the icon too. You are requesting to put additional files (not just overriding default ones) into the specific bundle-folder, this feature currently is not provided by the javapackager, which is inside the JDK, but it is no bug (just some inconvenience ... or just not-yet-implemented feature). I think they never got this far to think about their whole process of bundling javafx-applications on the mac, dont know, just my own thought.
