### ISSUE TITLE
How to package a 32 bit installer on a 64 bit machine?

### ISSUE THREAD

**Issue by maxiwu** [javafx-maven-plugin/javafx-maven-plugin#305] opened 2017-08-18 07:14 UTC
The correct configuration and properties to use in pom?
I have installed 32 bit JDK 1.8.0u114 on that machine.

**Comment by FibreFoX** [comment] 2017-08-18 11:15
Duplicate of #81

You have to run maven with the correct JDK configured. This means you can't create 32bit installers with some 64bit JDK (due to the binary-problem).

* first run: JAVA_HOME pointing to 32bit JDK (creates a 32bit installer/native launcher)
* second run: JAVA_HOME pointing to 64bit JDK (creates a 64bit installer/native launcher)

I already have checked the usage of [maven toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html), but I cant use that, because the whole bundling-process depends on the loaded modules/libs inside the maven-java-process.

**Closed by FibreFoX** 2017-08-18 11:15 UTC
