### ISSUE TITLE
Bundling all the file inside JRE

### ISSUE THREAD

**Issue by rahulvsin** [javafx-maven-plugin/javafx-maven-plugin#350] opened 2018-07-18 09:38 UTC
Hii, 
I'm using the javafx-maven-plugin for creating native installer. It works fine. Inside runtime folder I would like to have all the files from JRE. but now .exe file are missing. Could you please tell me how can achive this. Is there any tag i can use in the pom file to achieve the same. I have searched inside javafx:native goal documentation, but I couldn't find anything helpful. 
Can you please help me on this. Thank you!

**Comment by FibreFoX** [comment] 2018-07-18 15:56
Hi @rahulvsin, thanks a lot for getting in touch, but unfortunately this is intended behaviour. The JDK-provided `javapackager` strips the JRE down, including the native binaries.

Why is that so: the native launchers are including the JVM via DLL/SO-files being loaded, they do use the "direct" way instead of using the `java`-command binary. Why they decided so: probably security-reasons, because older JREs might contain security-bugs, which can be used as a trojan horse/jumphost process.

As this is "just a wrapper", this can't be fixed via this maven-plugin (at least I'm not aware of a way for changing these filters).

**Closed by FibreFoX** 2018-07-18 15:56 UTC
Labels: It's the JDK, wontfix
