### ISSUE TITLE
Inno Setup config file is not getting picked up

### ISSUE THREAD

**Issue by McRender** [javafx-maven-plugin/javafx-maven-plugin#280] opened 2017-02-09 09:48 UTC
Sometimes when building a clean project the .iss setup file is not getting picked up. I put the file under `src\main\deploy\package\windows\myProject.iss` but when building the default template is used.

This is my pom.xml:

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.2-SNAPSHOT</version>
    <configuration>
        <mainClass>xxx.xxxx.xxxx.xxxx</mainClass>
        <verbose>true</verbose>
        <vendor>xxxxx</vendor>
        <appName>myProject</appName>
        <bundleArguments>
            <licenseFile>License.txt</licenseFile>
        </bundleArguments>
        <additionalAppResources>${project.basedir}/src/main/additionalAppRessources</additionalAppResources>
    </configuration>
    <executions>
        <execution>
            <!-- required before build-native -->   
            <id>create-jfxjar</id>
            <phase>package</phase>
            <goals>
                <goal>build-jar</goal>
            </goals>
        </execution>
        <execution>
            <id>create-native</id>
            <phase>package</phase>
            <goals>
                <goal>build-native</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Am I missing something?

**Comment by FibreFoX** [comment] 2017-02-09 10:13
"Sometimes" makes me wonder?!? Normally `<appName>` is used to avoid name-changes regarding version-numbers. Maybe something with case-sensitivity on windows-filesystems?

**Comment by McRender** [comment] 2017-02-09 10:15
So the <appName> must correspond with the .iss file right?

**Comment by FibreFoX** [comment] 2017-02-09 10:18
it must correspond with `<appName>`, right

**Comment by FibreFoX** [comment] 2017-02-09 10:47
Still what do you mean by "sometimes"? Can you reproduce this? Maybe something IDE-related?

**Comment by McRender** [comment] 2017-02-09 10:48
I'am still trying to understand whats going wrong. With a fresh created maven project I do not have any problems. But when using an existing project the .iss file is not getting picked up.

**Comment by FibreFoX** [comment] 2017-02-09 10:59
normal steps for debugging:
* set `<verbose>true</verbose>`
* checking all file-positions (especially on multi-pom-projects, where you have a aggregator-pom, there might be some confusions about the file locations)

What is the build-process printing out? You should see the "expected" filename inside that build log.

**Comment by McRender** [comment] 2017-02-09 11:02
Allways gettings this:

`Using default package resource [Inno Setup project file]  (add package/windows/hans.iss to the class path `

**Comment by FibreFoX** [comment] 2017-02-09 11:03
Can you try to strip your project down and post it here, or mailing it to me (in the case it shouldn't be public)?

**Comment by McRender** [comment] 2017-02-09 11:06
I can't send you the whole project but I could invite you to a teamviewer session?

**Comment by FibreFoX** [comment] 2017-02-09 11:08
Thats why I asked for a stripped down project :) maybe you can re-create the project-structure in a sample project. It probably is a problem with your file-structure, as it works on some "fresh" project. Take a close look if you have folder-names like "packages" or "package", which often is it for me.

**Comment by McRender** [comment] 2017-02-09 11:14
Could it be because I have other folders beside the deploy and java folder inside the main folder? 

![grafik](https://cloud.githubusercontent.com/assets/5795337/22781085/5f161fd2-eec1-11e6-8868-dceb0bde0206.png)

**Comment by FibreFoX** [comment] 2017-02-09 11:17
Don't think so, because the MOJO does not look aside of it: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/AbstractJfxToolsMojo.java#L105
So I can assume that the project is no parent-pom project, right? Please check the folder naming of the subfolders, it sure is some typo, maybe the file-extension on windows are hidden and you have `appname.iss.iss`?

**Comment by McRender** [comment] 2017-02-09 11:27
I think I've found the bad boy:

```
<plugin> 
    <groupId>com.googlecode.addjars-maven-plugin</groupId> 
    <artifactId>addjars-maven-plugin</artifactId> 
    <version>1.0.5</version> 
    <executions> 
        <execution> 
            <goals> 
                <goal>add-jars</goal> 
            </goals> 
            <configuration> 
                <resources> 
                    <resource> 
                        <directory>${basedir}/src/main/additionalAppRessources/lib/</directory> 
                    </resource> 
                </resources> 
            </configuration> 
        </execution> 
    </executions> 
</plugin>
```

I'am using this plugin to copy all files in the specific folder when deploying. Somehow this plugin seems to mess around with the native deployment.

**Comment by FibreFoX** [comment] 2017-02-09 11:29
Normally all dependencies are already copied into the app-bundle, so no need for this. But I am happy that you found the problem (even if it is confusing).

Thanks for reporting and documenting that bit of information.

Can you close this issue now, or is there still something not working?

**Comment by McRender** [comment] 2017-02-09 12:32
Doh, there is still something not clear for me. Since I'am using 3th party librarys that are not jet part of a maven repository I need a way to include them in the classpath of the loader. Do you have any idea how to do this with the maven-plugin?

**Comment by FibreFoX** [comment] 2017-02-09 12:54
Just a assumption: you have these libs inside the additionalAppResources-folder, right? You can try the new flag which got introduced with 8.8.0, simply set `<useLibFolderContentForManifestClasspath>true</useLibFolderContentForManifestClasspath>`.

Just copy the "private" files into the `target/jfx/app/lib`-location before the javafx-maven-plugin runs, than all files should get added to the classpath. Meanwhile I am thinking about some additional flag about "additionalAppResources" being copied before, making it obsolete to configure this additional copy-task with a different maven-plugin.

**Comment by McRender** [comment] 2017-02-09 13:04
Jep, your assumption is right. I'll give it a try and yeah, it would be greate to make it obsolete the additional copy-task. Let me know if you need a tester :-)

**Comment by FibreFoX** [comment] 2017-02-09 13:11
Will close this, nothing iss-related anymore. If you feel like requiring answer, but dont want to create an issue on the project, you can send me questions via e-mail.

**Closed by FibreFoX** 2017-02-09 13:11 UTC
Labels: question
