### ISSUE TITLE
"Main application jar is missing", if you rename main jar with <jfxMainAppJarName>

### ISSUE THREAD

**Issue by pjBooms** [javafx-maven-plugin/javafx-maven-plugin#59] opened 2014-05-18 17:58 UTC
I have tried to customize main jar name with <jfxMainAppJarName> but now, native packaging stage is skipping due to the following:

  Skip [Windows Application Bundler] due to [Main application jar is missing.]
   [Make sure to use fx:jar task to create main application jar.]

However it works if you specify the name with the ".jar" extension

**Comment by javasparx** [comment] 2015-03-03 17:48
you right man, thank you.

**Comment by FibreFoX** [comment] 2015-05-02 22:34
I can't reproduce this anymore, maybe its already fixed with other changes. Please retry with current master and re-open this issue if needed.

**Closed by FibreFoX** 2015-05-02 22:34 UTC
