### ISSUE TITLE
Building native installer with JNI access

### ISSUE THREAD

**Issue by McRender** [javafx-maven-plugin/javafx-maven-plugin#276] opened 2017-02-08 10:58 UTC
I'am trying to use your plugin to build a native installer for my JavaFX application that uses some native librarys. When ever I am running my application directly from .jar file (java -jar myApplication.jar, even with the bundled JRE) everything works as expected. However when building a native installer the application crashes as soon as I run the .exe file. It looks like there is a problem accessing the native interface:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=9728, tid=0x0000000000000d0c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
.....
```

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J+0
j  jssc.SerialPort.openPort()Z+65
j  com.mycompany.jssclab.JSSCLab.start(Ljavafx/stage/Stage;)V+144
```

Do I need to add specific paths to my .dll files in the configuration file to be able to call System.load()? Pleas let me know if you have any idea how to solve this issue. 

Thank you very much in advance for your help.

**Comment by FibreFoX** [comment] 2017-02-08 11:37
I need a stripped down project, where I can reproduce this problem. As this plugin is only a (more or less clever) wrapper around the javapackager, this might be a problem with the JDK itself.

**Comment by McRender** [comment] 2017-02-08 11:57
Let me prepare a sample project for this. I'll post the link here as soon as I am ready.

**Comment by FibreFoX** [comment] 2017-02-08 12:08
No problem, take your time ;)

**Comment by McRender** [comment] 2017-02-08 12:09
I've created the sample appication as a Netbeans project. I was somehow not able to upload the .zip file as an attachement but here is the linke: [Sample Project](http://www.raible.ch/files/JSSCNativeLab.ZIP)

Let me know if you need anything else. You can also reach my by Skype or Email if it helps.

**Comment by FibreFoX** [comment] 2017-02-08 12:14
Thanks for the project! Seems like you tried to migrate from the javapackager to the javafx-maven-plugin ;)

You might want to create a github-project for this instead of uploading somewhere, but uploading zip-files is okay for me.

If I found something, I will report back.

**Comment by FibreFoX** [comment] 2017-02-08 12:31
I have reworked the pom.xml, and can create a working native launcher.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany</groupId>
    <artifactId>JSSCNativeLab</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>JSSCNativeLab</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.1</version>
                <configuration>
                    <mainClass>com.mycompany.jsscnativelab.MainApp</mainClass>
                    <verbose>true</verbose>
                    <vendor>Your Organisation</vendor>
                    <bundler>windows.app</bundler>
                </configuration>
                <executions>
                    <execution>
                        <!-- required before build-native -->
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>create-native</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-native</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.scream3r</groupId>
            <artifactId>jssc</artifactId>
            <version>2.8.0</version>
        </dependency>
    </dependencies>
</project>
```

Please note, that I removed the other build-plugins and fixed the bundler to create only the native windows-binary.

If you call `mvn clean package`, it generates everything, but despite of the bug in #275, this works for me. Did I miss something?

**Comment by McRender** [comment] 2017-02-08 12:31
Did you hit the button? As soon as you hit it, the application should crash.

**Comment by FibreFoX** [comment] 2017-02-08 12:34
![jfxmp-issue276-screen1](https://cloud.githubusercontent.com/assets/1042579/22737421/4a1d63ba-ee03-11e6-8189-db3ed7ac01eb.PNG)
![jfxmp-issue276-screen2](https://cloud.githubusercontent.com/assets/1042579/22737428/4c0a11e6-ee03-11e6-86c5-e73ce3832273.PNG)

Working on Windows 10, 64bit, with 64bit Oracle JDK

**Comment by McRender** [comment] 2017-02-08 12:37
Oh dam... I see. Do you have an USB Serial Port adapter or a hardware COM port in your computer? Otherwise there won't be a call to the native dll I think.

**Comment by McRender** [comment] 2017-02-08 12:40
![grafik](https://cloud.githubusercontent.com/assets/5795337/22737614/1a0b7c42-ee04-11e6-8363-49580b23a4b8.png)

**Comment by McRender** [comment] 2017-02-08 12:41
![grafik](https://cloud.githubusercontent.com/assets/5795337/22737648/488cd94e-ee04-11e6-9433-2b035c7de1e1.png)

**Comment by FibreFoX** [comment] 2017-02-08 12:41
Give me a second ;) will have to use a different computer for this.

**Comment by McRender** [comment] 2017-02-08 12:43
Too good :-). It might be that you have to change the value for the com port according to your system.

**Comment by FibreFoX** [comment] 2017-02-08 13:08
I can confirm this faulty behaviour, but this might be that library you are using. I am very sorry, but I have to close this issue as invalid, because it does not have anything to do with the javafx-maven-plugin, but the native launcher (which comes from the JDK) and that lib in combination, maybe the developers of jssc can help you here :(

**Closed by FibreFoX** 2017-02-08 13:08 UTC
Labels: native launcher, needs investigation, Windows

**Comment by McRender** [comment] 2017-02-08 13:17
Thanks anyway for looking into this. Your sure it has nothing to do with the way the native libs are handled by the maven-plugin (see [)Eample 6.8](http://docs.oracle.com/javafx/2/deployment/self-contained-packaging.htm)

**Comment by FibreFoX** [comment] 2017-02-08 13:25
The maven-plugin has nothing to do with the final created exe-file.

Just a small excerpt, how this works:
* the created exe-file is a dumb launcher, a generic one where the filename is relevant to find the  `.cfg`-file inside the app folder
* one of the first things, which get loaded, is the `packager.dll`
* this dll looks for the JRE-file to load (http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/fe6b492b9150/modules/fxpackager/src/main/native/library/common/JavaVirtualMachine.cpp#l418 http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/fe6b492b9150/modules/fxpackager/src/main/native/library/common/WindowsPlatform.cpp#l256 .. some older commits, but still relevant)
* this means that loading the JNI should work "like in normal exe-files", if it fails, it must fail because of a different problem, most likely the native launcher (which comes precompiled from the JDK) or the used dll

**Comment by McRender** [comment] 2017-02-08 13:28
I can confirm this. The maven-plugin has nothing to do with my problem. I am facing the same problem when using the ANT-way to build my installer. Thank you very much for looking into this.

**Comment by McRender** [comment] 2017-02-08 15:30
For those who are interested in this topic, I can confirm this issue is not related specific to the jssc library. I've tested another native library and I still have the same problem. Must be an problem with the native launcher :(.

**Comment by FibreFoX** [comment] 2017-02-08 15:40
@McRender Can you check if this is windows-specific? Did you try this on Linux/Mac?

**Comment by McRender** [comment] 2017-02-08 15:45
Ok... got some progress on this. When using the other serial port library I was able to communicate over the port when I just copied the .dll to the app folder and startet the .exe file. 

When using the jssc library the .dll file will be copied to my User folder under .jssc but no luck so far executing the application without a crash.

I don't have any linux or mac os devices here at the moment.
