### ISSUE TITLE
build-jar failed: A required class was missing while executing com.zenjava:javafx-maven-plugin:8.1.4:build-jar: com/oracle/tools/packager/Log$Logger

### ISSUE THREAD

**Issue by tarkal** [javafx-maven-plugin/javafx-maven-plugin#197] opened 2016-03-29 09:33 UTC
This is the same issue reported in #166 but for **OSX **instead of **Windows**. During the build phase the following error is encountered and the build fails:

```
[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ codebox ---
[INFO] Building jar: /Users/user/Desktop/codebox/target/codebox-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- javafx-maven-plugin:8.1.4:build-jar (create-jfxjar) @ codebox ---
[INFO] Building JavaFX JAR for application
[WARNING] Skipped checking for packager.jar. Please install at least Java 1.8u40 for using this feature.
[INFO] Adding 'deploy' directory to Mojo classpath: /Users/user/Desktop/codebox/src/main/deploy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.360s
[INFO] Finished at: Tue Mar 29 11:20:44 CEST 2016
[INFO] Final Memory: 8M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.1.4:build-jar (create-jfxjar) on project codebox: Execution create-jfxjar of goal com.zenjava:javafx-maven-plugin:8.1.4:build-jar failed: A required class was missing while executing com.zenjava:javafx-maven-plugin:8.1.4:build-jar: com/oracle/tools/packager/Log$Logger
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.zenjava:javafx-maven-plugin:8.1.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/user/.m2/repository/com/zenjava/javafx-maven-plugin/8.1.4/javafx-maven-plugin-8.1.4.jar
[ERROR] urls[1] = file:/Users/user/.m2/repository/org/twdata/maven/mojo-executor/2.2.0/mojo-executor-2.2.0.jar
[ERROR] urls[2] = file:/Users/user/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[3] = file:/Users/user/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[4] = file:/Users/user/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[5] = file:/Users/user/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/Users/user/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/Users/user/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/Users/user/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/Users/user/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
[ERROR] urls[10] = file:/Users/user/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
[ERROR] urls[11] = file:/Users/user/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar
[ERROR] urls[12] = file:/Users/user/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.5/maven-shared-utils-0.5.jar
[ERROR] urls[13] = file:/Users/user/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[14] = file:/Users/user/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[15] = file:/Users/user/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar
[ERROR] urls[16] = file:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/../lib/ant-javafx.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.oracle.tools.packager.Log$Logger 
```

IntelliJ details:
![screen shot 2016-03-29 at 11 27 06](https://cloud.githubusercontent.com/assets/7042623/14103648/64d352ba-f5a1-11e5-9751-ad9d72707bde.png)

Maven Version 3.0.5

Example skeleton project
[test_maven_fx.zip](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/193180/test_maven_fx.zip)

**Comment by FibreFoX** [comment] 2016-03-29 09:49
Just to make sure: you can reproduce that issue with the project you've attached?

**Comment by tarkal** [comment] 2016-03-29 09:49
yes.

**Comment by FibreFoX** [comment] 2016-03-29 09:50
Oh, another thing: can you upgrade to plugin-version 8.4.0? Maybe the issue is gone already with that.

I've tried to reproduce on windows (don't have any osx-machine), but works normal for me.

**Comment by tarkal** [comment] 2016-03-29 09:53
8.4.0 stil causes the error. :(

N.B. I get the same issue with virtual Ubuntu system.

**Comment by FibreFoX** [comment] 2016-03-29 09:53
Thanks for the Ubuntu-hint. Which one: 16, 14, 12?

**Comment by tarkal** [comment] 2016-03-29 09:55
14.04.4 LTS -> I just created it for this experiment.

**Comment by FibreFoX** [comment] 2016-03-29 09:55
Oh, now I might have seen something: are you using "Oracle JDK" or "OpenJDK"? When using OpenJDK make sure to install OpenJFX too.

**Comment by FibreFoX** [comment] 2016-03-30 18:09
@tarkal I've installed a new VM with Ubuntu (version:14.04.3, architecture: amd64), which JDK did you install? Out-of-the-box there is no java available.

**Comment by tarkal** [comment] 2016-03-30 19:02
I installed oracle using 

add-apt-repository -y ppa:webupd8team/java

**Comment by FibreFoX** [comment] 2016-03-30 19:04
@tarkal  thanks for that information, will try to recreate that issue.

Were you using `apt-get install maven` or did you install it on another way?

**Comment by tarkal** [comment] 2016-03-30 19:06
No I used the IntelliJ built in maven.

**Comment by FibreFoX** [comment] 2016-03-30 19:23
@tarkal How did you install IntelliJ? Did you download it from [their download-page](https://www.jetbrains.com/idea/download/download-thanks.html?platform=linux&code=IIC) or did you use that ubuntu software-center? (Just want to make it as close at possible to your conditions)

**Comment by FibreFoX** [comment] 2016-03-30 19:57
I now have installed Ubuntu 14, Oracle 8 (via webupd8team), downloaded IntelliJ, imported the maven-project you provided ... but can't reproduce that issue. Note that IntelliJ comes with OpenJDK, so you might wan't to chance to that OracleJDK, [like described here](http://blog.jetbrains.com/idea/2015/05/intellij-idea-14-1-4-eap-141-1192-is-available/) using "Switch IDE Boot JDK"-feature.

I know it is hard, but could you provide every step to reproduce when having a clean ubuntu-vm?

**Comment by tarkal** [comment] 2016-03-31 07:20
Interesting, I wasn’t aware that the IDE was using its own JDK instead of the one I installed. I am traveling today but I will take a look later and report back.

**Comment by FibreFoX** [comment] 2016-03-31 08:49
@tarkal no problem, take your time :) that bug is somewhere correlated with IDEA IntelliJ, so it might take a while to reproduce ;)

**Comment by FibreFoX** [comment] 2016-04-05 18:15
@tarkal any progress on this issue?

**Comment by tarkal** [comment] 2016-04-06 00:37
Sorry I’m traveling until Monday. Ill take a look then.

**Comment by FibreFoX** [comment] 2016-04-06 08:00
@tarkal Okay, no problem :) didn't want to be pushy, I was just checking the issues on the project.

**Comment by FibreFoX** [comment] 2016-04-15 07:14
@tarkal I'll close this issue in the next days when no further feedback was provided. It must have been something with IDEA itself, so this might not even be related to the javafx-maven-plugin anyway.

**Comment by tarkal** [comment] 2016-04-15 07:17
I’m really sorry, my work trip was extended by a month and I haven’t had time to look at this. Feel free to close it and I will re-open it if need be when I get a chance to look into it again. Thanks

**Comment by FibreFoX** [comment] 2016-04-15 08:12
@tarkal that sounds like a plan ;) I just get itchy when having no response for a long time.

**Closed by FibreFoX** 2016-04-15 08:12 UTC
Labels: IDE-related, Linux, Mac, needs investigation

**Comment by toolforger** [comment] 2016-08-25 16:12
(Sorry for necroing this, this page was among the first search results.)
Not sure whether I have the same problem, but it definitive sounds related.

Ubuntu 16.04 LTS here.
Activating the UserJvmOptionsService tries to find packager.jar at `"${System.properties['java.home']}/../lib/packager.jar"`, which resolves to `/usr/lib/jvm/java-8-openjdk-amd64/lib/packager.jar`.
However, the actual file location is `/usr/share/java/openjfx/packager.jar` - I don't know what the "official" way to find the jfx jars is, but it seems that java.home isn't it.

No Java-related environment variables are set; in particular, there is no JAVA_HOME.

**Comment by FibreFoX** [comment] 2016-08-25 16:54
@toolforger not even slightly related .. please open a separated issue, are you sure that you are meaning the javafx-MAVEN-plugin?

**Comment by toolforger** [comment] 2016-08-25 21:17
Indeed that was from the gradle plugin.
Didn't notice it's for the other build tool.

If both plugins follow the same logic, this might still be what's affecting @tarkal .
This is just an observation that I made in passing and thought it might be helpful; if it isn't, please ignore.

**Comment by FibreFoX** [comment] 2016-08-25 21:43
@toolforger as I said, it is not related, please open a new issue on the other project, it belongs there

**Comment by FibreFoX** [comment] 2016-08-26 07:27
@toolforger I've updated the README.md of the javafx-gradle-plugin, take a close look at the configuration of the dependencies, you will find your anweser there, otherwise please don't spam this thread, create a new/fresh one to not irritate @tarkal nor other users using searchengines for this
